{{- if .Values.global.enabled_aws_upbound }}

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-aws
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  package: {{ $.Values.global.aws_upbound_registry }}/provider-family-aws:{{ $.Values.global.aws_upbound_version }}

{{- end }}