apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-sm
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: private-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sm
    kind: ClusterSecretStore
  target:
    name: private-repo-creds
    deletionPolicy: "Retain"
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        sshPrivateKey: '{{ .key }}'
        url: git@github.com:aws-samples
        type: git
  data:
  - secretKey: key
    remoteRef:
      key: github-ssh-key