{{- if .Values.headRoom -}}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: karpenter-headroom
value: -1000000
globalDefault: false
description: "Used for dummy pods to generate headroom in karpenter"
{{- end -}}
