global:
  enabled_aws: false
  iam_role_arn_aws: null
  enabled_aws_upbound: true
  iam_role_arn_aws_upbound: null
  enabled_kubernetes: true
  enabled_helm: true


aws-upbound:
  providers:
  - cloudfront
  - cloudwatchlogs
  - dynamodb
  - ec2
  - eks
  - firehose
  - iam
  - kms
  - lambda
  - rds
  - s3
  - sns
  - sqs
