{{- if .Values.enabled }}
kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  parsers.conf: |
{{ .Values.parser | indent 4 }}
  filters.conf: |
{{ .Values.filters | indent 4 }}
  output.conf: |
{{ tpl .Values.output $ | indent 4 }}
  flb_log_cw: {{ .Values.flb_log_cw | quote }}

{{- end }}