{
 "title": "Karpenter-for-export",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "perc", "label": "Percentile", "query": "0.5, 0.8, 0.9,1" },
   { "name": "timediff", "query": "1d,2d,5d,7d,14d,30d,60d,90d" },
   { "name": "CLUSTER", "query": { "query": "label_values(cluster)" } },
   {
    "name": "quantile",
    "query": {
     "query": "label_values(karpenter_nodes_termination_time_seconds,quantile)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_time_seconds_count, controller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$CLUSTER Total Interruptions - during $timediff",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "repeat": "CLUSTER",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodeclaims_terminated{reason=\"interruption\",cluster=~\"$CLUSTER\"}) by (nodepool) - (sum(karpenter_nodeclaims_terminated{reason=\"interruption\",cluster=~\"$CLUSTER\"}) by (nodepool) offset $timediff)",
     "legendFormat": "{{nodepool}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"karpenter.*\"})) by (cluster, pod)",
     "legendFormat": "[{{cluster}}]{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"karpenter.*\"}) by (cluster, pod)",
     "legendFormat": "[{{cluster}}]{{pod}}"
    }
   ]
  },
  { "title": "Cluster Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Spot/OD by Provisioners - $CLUSTER",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "repeat": "CLUSTER",
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=~\"$CLUSTER\",label_karpenter_sh_capacity_type!=\"\"}) by (label_karpenter_sh_nodepool, label_karpenter_sh_capacity_type)",
     "legendFormat": "[{{label_karpenter_sh_capacity_type}}]{{label_karpenter_sh_nodepool}} "
    },
    {
     "expr": "count(kube_node_labels{cluster=~\"$CLUSTER\",label_karpenter_sh_capacity_type!=\"\"}) by ( label_karpenter_sh_capacity_type)",
     "legendFormat": "TOTAL [{{label_karpenter_sh_capacity_type}}]"
    }
   ]
  },
  {
   "title": "NodeGroup Usage Out Of limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodepool_usage) by (cluster, nodepool, resource_type) / sum(karpenter_nodepool_limit) by (cluster, nodepool, resource_type)",
     "legendFormat": "[{{cluster}}] {{nodepool}} {{resource_type}}"
    }
   ]
  },
  { "title": "Provisioning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Created/Removed Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(karpenter_nodeclaims_created[1m])) by (cluster, nodepool, reason)",
     "legendFormat": "[A][{{cluster}} {{nodepool}}]{{reason}}"
    },
    {
     "expr": "- sum(increase(karpenter_nodeclaims_terminated[1m])) by (cluster, reason, nodepool)",
     "legendFormat": "[R][{{cluster}} {{nodepool}}]{{reason}}"
    }
   ]
  },
  {
   "title": "Karpenter Spot Interruptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(idelta(karpenter_nodeclaims_terminated{reason=\"interruption\"}[1m])) by (nodepool, cluster)",
     "legendFormat": "[{{cluster}}] {{nodepool}}"
    }
   ]
  },
  {
   "title": "Instance Provisioning Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(irate(karpenter_cloudprovider_duration_seconds_count{method!=\"GetInstanceTypes\"}[1m])) by (cluster, method) * 60",
     "legendFormat": "{{cluster}} {{method}}"
    }
   ]
  },
  {
   "title": "Interruption actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(karpenter_interruption_actions_performed[1m])) by (action_type,cluster)",
     "legendFormat": "[{{cluster}}]{{action_type}}"
    }
   ]
  },
  {
   "title": "Deprovisioning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(karpenter_deprovisioning_actions_performed[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "AWS Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($perc, sum(rate(karpenter_cloudprovider_duration_seconds_bucket{method!=\"GetInstanceTypes\"}[5m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Interruption messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(irate(karpenter_interruption_received_messages[1m])) by (message_type, cluster) * 60",
     "legendFormat": "{{cluster}}_{{message_type}}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Workers Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{service=\"karpenter\"}) by (cluster, controller) / sum(controller_runtime_max_concurrent_reconciles{service=\"karpenter\"}) by (cluster, controller)",
     "legendFormat": "[{{cluster}}] {{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile errors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{service=\"karpenter\"}[5m])) by (cluster, controller)",
     "legendFormat": "[{{cluster}}] {{controller}}"
    }
   ]
  },
  {
   "title": "Controller Reconciliation Latency [$controller]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($perc, rate(controller_runtime_reconcile_time_seconds_bucket{controller=~\"$controller\",cluster=~\"$CLUSTER\"}[10m]))",
     "legendFormat": "[$perc {{controller}}] {{cluster}}"
    }
   ]
  },
  {
   "title": "Controller Reconciliation Rate",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster=~\"$CLUSTER\",controller=~\"$controller\"}[10m])) by (controller,cluster)",
     "legendFormat": "[{{cluster}}]{{controller}}"
    }
   ]
  },
  {
   "title": "Node Termination Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "karpenter_nodes_termination_time_seconds{quantile=\"$quantile\"}",
     "legendFormat": "[$quantile][{{cluster}}]{{nodepool}}"
    }
   ]
  }
 ]
}