{{- $environment := .Values.environment | default .Values.global.environment -}}
{{-  if eq $environment "production" -}}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: on-demand
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h0m0s
  limits:
    cpu: 1k
  template:
    metadata:
      labels:
        bottlerocket.aws/updater-interface-version: 2.0.0
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
      - key: capacity-spread
        operator: In
        values:
        - "1"
        - "2"
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "8"
        - "16"
        - "32"
        - "48"
        - "64"
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "4"
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      {{- with .Values.startupTaints }}
      startupTaints:
      {{- toYaml . | nindent 6 }}
      {{ end }}
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h0m0s
  limits:
    cpu: 1k
  template:
    metadata:
      labels:
        bottlerocket.aws/updater-interface-version: 2.0.0
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
      - key: capacity-spread
        operator: In
        values:
        - "3"
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
        - spot
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "8"
        - "16"
        - "32"
        - "48"
        - "64"
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "4"
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      {{- with .Values.startupTaints }}
      startupTaints:
      {{- toYaml . | nindent 6 }}
      {{ end }}
{{- else -}}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h0m0s
  limits:
    cpu: 1k
  template:
    metadata:
      labels:
        bottlerocket.aws/updater-interface-version: 2.0.0
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "8"
        - "16"
        - "32"
        - "48"
        - "64"
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "4"
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      {{- with .Values.startupTaints }}
      startupTaints:
      {{- toYaml . | nindent 6 }}
      {{ end }}
{{- end -}}