tenants:
  tenant1:
    stack_version: v2
    environments:
      dev:
        stack_version: v2
      staging:
        stack_version: v1
      prod:
        stack_version: v2
    clusters:
      cluster1:
        stack_version: v2
